version: '3'

services:
  django: &django
    image: shevchenkoigor/panda:telegram_bot_test
    restart: on-failure
    depends_on:
      - postgres
      - mailhog
      - elasticsearch
    volumes:
      - .:/app
      - ~/.ipython:/root/.ipython
    env_file:
      - ./.envs/.test/.django
      - ./.envs/.test/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: test_panda_postgres
    env_file:
      - ./.envs/.test/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: shevchenkoigor/panda:telegram_bot_test
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: shevchenkoigor/panda:telegram_bot_test
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: shevchenkoigor/panda:telegram_bot_test
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/test/node/Dockerfile
    image: panda_test_node
    depends_on:
      - django
    volumes:
      - .:/app
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev

  elasticsearch:
    image: elasticsearch:2
