# Generated by Django 2.2.4 on 2020-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_product_media_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='message_id',
            field=models.IntegerField(db_index=True, unique=True),
            preserve_default=False,
        ),
    ]
