# Generated by Django 2.2.4 on 2020-02-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_product_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='message_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
